[package]
name = "sdk-client"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
domain = { path = "../domain" }
platform = { path = "../platform" }
runtime-ipc = { path = "../runtime-ipc" }
sdk-ffi = { path = "../sdk-ffi" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
